### PR TITLE
⚙️ : Unify config file & Github automation.

### LINKED ISSUE #12: Github helpers to create or check repositories

### LINKED ISSUE #18: ⚙️ Merge all commands configs on a single config file.
Hey guys, currently the CLI is managing the configuration for multiples commands on diferrent files inside of the config folder. 

I was wondering if we can do a helper to manage a single config file entrypoint to sabe all the config data related.

Each command can have a configure action and update on the single config file their data related; the file schema can be:

```js
{
   action: {
          configName: DATA
    }
}
```

### PR DESCRIPTION
**Pull request by AndresMorelos**
Fix #18 
Fix #12 

## Config file preview
```js
{
     "health": {
          "github": {
               "status": "https://www.githubstatus.com/api/v2/status.json",
               "rss": "https://www.githubstatus.com/history.rss",
               "indicators": {
                    "none": "green"
               }
          },
          "trello": {
               "status": "https://trello.status.atlassian.com/api/v2/status.json",
               "rss": "https://trello.status.atlassian.com/history.rss",
               "indicators": {
                    "none": "green"
               }
          },
          "jira": {
               "status": "https://jira-software.status.atlassian.com/api/v2/status.json",
               "rss": "https://jira-software.status.atlassian.com/history.rss",
               "indicators": {
                    "none": "green"
               }
          }
     }
}
```

### CODE REVIEW

**Comment by AndresMorelos** [comment]
@clouby @FlavioAandres could you please take a look at this PR?

**Comment by FlavioAandres** [comment]
@AndresMorelos Hey dude, it is a great idea, thanks for developing it, let me some time to check if all functionalities are working as we expected!

**Comment by clouby** [comment]
Hey @AndresMorelos I checked that there are two PR with almost the same commits what's the different between them ? 😅

**Comment by AndresMorelos** [comment]
> Hey @AndresMorelos I checked that there are two PR with almost the same commits what's the different between them ? 😅

@clouby This PR was merged into the Github automation PR to implement the functionality on the command; That's the difference, We can merge this one first and then the Github automation.




> @AndresMorelos Hey dude, it is a great idea, thanks for developing it, let me some time to check if all functionalities are working as we expected!

@FlavioAandres On this PR all of the commands work with this functionality as expected, take a look.

**Comment by FlavioAandres** [comment]
@AndresMorelos 
Hey i was checking all the commands and all of them works as it should butt, i could not delete a repository created from the daily-cli, here i found this error: 

image

i had to add a `console.log` to see the error, i suggest you add the `error.message` in the error log for the user 

This is the only feedback that i've for you ⚡

**Comment by AndresMorelos** [comment]
@FlavioAandres Two things:

1. That day Github services had some issues.
2. Make sure that your token has the `delete_repo` access.

**Comment by FlavioAandres** [comment]
Now i was able to delete the repository, thanks for the changes on the logs and documentation, i think that was what happened, i was missing the deletion permissions

image

**Review by FlavioAandres — APPROVED** [review]
i've checked the code and all works as we expected, good job 🚀

**Comment by AndresMorelos** [comment]
@FlavioAandres @clouby Please merge this PR when you've time

**Pull request merged**
